site: coder seventeen
title: coder seventeen
description: >-
  just a minimalist, personal blog
googlewebfonts: Hepta+Slab:wght@400;600;700

lang: en-US
timezone: Ho_Chi_Minh
repo: # site repo [optional]
data-theme: dark # default theme "dark" | "light"

author:
  name: Huy Pham
  bio: just a minimalist, personal blog
  username: Huy Pham # general username
  github:  coder7eeN# github username
  twitter: # twitter username
  email: phamnguyenanhhuy@email.com # email adress

# URL settings
url: "https://coder7een.github.io" # url for runing server
baseurl: "" # leave blank if not wishd
permalink: # static link
permalink: pretty 


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false
