site: coder seventeen
title: coder seventeen
description: >-
  Huy's blog
googlewebfonts: Be+Vietnam:wght@300 #more size: wght@300;500;700

lang: en-US
timezone: Ho_Chi_Minh
repo: # site repo [optional]
data-theme: dark # default theme "dark" | "light"

author:
  name: Huy Pham
  bio: just a minimalist blog
  username: Huy Pham # general username
  github:  coder7eeN# github username
  twitter: # twitter username
  email: phamnguyenanhhuy@email.com # email adress

# URL settings
url: "https://coder7een.github.io" # url for runing server
baseurl: # use for hostname ex: /seventeen, leave blank if it doesn't have
permalink: # static link
permalink: pretty 


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false

# You must install giscus github app before use.(https://github.com/apps/giscus)
# Make sure all variables are set properly. Check below link for detail.
# https://giscus.vercel.app/
giscus:
  repo: "coder7eeN/coder7eeN.github.io"
  repo-id: "MDEwOlJlcG9zaXRvcnkzMjY1NDEwNDc="
  category: "Comments"
  category-id: "DIC_kwDOE3ae984B-YOl"
  mapping: "title"
  reaction-enabled: "1"
  theme: "dark"
  crossorigin: "anonymous"